# AUTHOR: Giorgio Antonacci

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sports-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sports-consumer
  template:
    metadata:
      labels:
        app: sports-consumer
    spec:
      containers:
      - name: consumer
        image: 10.56.3.197:5000/sports-consumer
        imagePullPolicy: Always
