# AUTHOR: Giorgio Antonacci

---
- name: Build, push, and run sports producers
  hosts: master
  become: true
  vars:
    docker_registry: "10.56.3.197:5000"
    remote_user_home: "/home/cc"
    producers:
      - name: mbball
      - name: wbball
      - name: mfootball

  tasks:
    - name: "Build Docker image for each producer"
      command: >
        docker build -f dockerfile -t {{ item.name }}-producer .
      args:
        chdir: "{{ remote_user_home }}/docker/producers/{{ item.name }}"
      loop: "{{ producers }}"

    - name: "Tag image for private Docker registry"
      command: >
        docker tag {{ item.name }}-producer:latest {{ docker_registry }}/{{ item.name }}-producer
      loop: "{{ producers }}"

    - name: "Push image to private Docker registry"
      command: >
        docker push {{ docker_registry }}/{{ item.name }}-producer
      loop: "{{ producers }}"

    - name: "Remove local image: untagged (latest)"
      command: >
        docker rmi {{ item.name }}-producer:latest
      ignore_errors: yes
      loop: "{{ producers }}"

    - name: "Remove local image: registry-tagged"
      command: >
        docker rmi {{ docker_registry }}/{{ item.name }}-producer
      ignore_errors: yes
      loop: "{{ producers }}"

    - name: "Run the producer container from private registry"
      command: >
        docker run -it --rm {{ docker_registry }}/{{ item.name }}-producer
      args:
        chdir: "{{ remote_user_home }}/docker/producers/{{ item.name }}"
      loop: "{{ producers }}"
